### ISSUE TITLE
File 'RoleRepository.cs' has a small error

### ISSUE THREAD

**Issue by suchafool** [radenkozec/MySqlIdentity#9]
MySqlHelper.ExecuteNonQuery(conn, @"INSERT INTO aspnetroles (Id, Name) VALUES (@name, @id)", parameters);

Notice the sql statement, those two values are reversed.

**Comment by cedisoftsrl** [comment]
Hi, thanks for the notice. 

Yes I Know.. and actually I did the fork to solve this problem and try to continue development.

Thank you!
Roberto

**Comment by radenkozec** [comment]
I have pushed fix for this issue.Thanks for reporting.
